# Generated by Django 4.0.3 on 2024-03-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_room_participants'),
        ('base', '0003_user_avatar'),
    ]

    operations = [
    ]
